---
apiVersion: k3d.io/v1alpha2
kind: Simple
name: dev
servers: 1
agents: 2
ports:
  - port: 8000:80
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraServerArgs:
    - --disable=traefik
    - --disable=metrics-server
    - --node-label=svccontroller.k3s.cattle.io/enablelb=true
